---
- name: Setup development environment
  hosts: localhost
  connection: local
  tasks:
    ## apt
    - name: Update repository cache
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Install packages
      become: true
      apt:
        name:
          - "{{ item }}"
        state: latest
      loop:
        - git
        - curl
        - fzf
    ## dotfiles
    - name: Setup dotfiles
      shell: curl -s {{ installer }} | /bin/bash
      vars:
        installer: https://raw.githubusercontent.com/peg7/dotfiles/main/.bin/install.sh
    ## starship

